name: OpenSSF Scorecard analysis

on:
  branch_protection_rule:
  workflow_dispatch:
  schedule:
    # Weekly on Sundays, 17:37 UTC.
    - cron: '37 17 * * 0'
  push:
    branches: [ main ]

# Declare default permissions as read-only.
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload results to GitHub code scanning.
      id-token: write # Needed to fetch GitHub OIDC token.

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: 'Run analysis'
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: 'Upload results to code scanning'
        uses: github/codeql-action/upload-sarif@8a470fddafa5cbb6266ee11b37ef4d8aae19c571 # v3.24.6
        with:
          sarif_file: results.sarif
